language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - yarn add coveralls

script:
  - yarn test-travis

notifications:
  slack: "${SLACK_CREDS}"
